buco/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('landinpage.urls', namespace='landinpage')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

landinpage/urls.py
from django.urls import path
from . import views
app_name = 'landinpage'

urlpatterns = [

    path('', views.index, name='index'),
    path('<str:title>/portofolio', views.portofolio, name='portofolio')
   
]

landinpage/models.py
from django.db import models
from django.urls import reverse
# Create your models here.
class MainSection(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    img = models.ImageField(upload_to='images')

    def __str__(self):
        return self.title


class Sector(models.Model):
    title = models.CharField(max_length=50)

    def __str__(self):
        return self.title


class Stat(models.Model):
    title = models.CharField(max_length=300)
    number = models.IntegerField()

    def __str__(self):
        return self.title


class Service(models.Model):
    title = models.CharField(max_length=150)
    description = models.TextField()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('landinpage:portofolio', args=[self.title])


class Project(models.Model):
    service = models.ForeignKey(Service, on_delete=models.CASCADE, related_name='services')
    title = models.CharField(max_length=150)
    description = models.TextField()
    category = models.CharField(max_length=150)
    client = models.CharField(max_length=150)
    project_date = models.DateField(auto_now=False, auto_now_add=False)
    project_url = models.URLField(max_length=250, blank=True)
    project_img = models.ImageField(upload_to='projects')

    def __str__(self):
        return self.title


class Team(models.Model):
    name = models.CharField(max_length=250)
    fonction = models.CharField(max_length=200)
    sector = models.ForeignKey(Sector, on_delete=models.CASCADE, related_name='team')
    team_img = models.ImageField(upload_to='team')   

    def __str__(self):
        return self.name


class BucoInfo(models.Model):
    adress = models.CharField(max_length=150)
    mail = models.EmailField(max_length=254)
    # num = models.PhoneNumberField()

    def __str__(self):
        return f"Buco information"
    

landinpage/forms.py
from django import forms

class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=50, required=True)
    email = forms.EmailField(required=True)
    subject = forms.CharField(max_length=250, required=True)
    message = forms.CharField(widget=forms.Textarea)

landinpage/views.py
from .forms import EmailPostForm
from django.core.mail import send_mail
from django.shortcuts import render, get_object_or_404 
from .models import MainSection, Sector, Stat, Service, Project, Team, BucoInfo
# Create your views here.

def index(request):
    sections = MainSection.objects.all()
    sectors = Sector.objects.order_by('title')
    stats = Stat.objects.all()
    services = Service.objects.all()
    teams = Team.objects.all()
    infos = BucoInfo.objects.first()
    sent = False
    # sending email setup
    if request.method == 'POST':
        # Form is submitted
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # Form field pass validation
            cd = form.cleaned_data
            subject = f"Mail de :{cd['name']}" + f' Objet du message:' + cd['subject']
            message = cd['message']
            email = cd['email']
            send_mail(subject, message, email, ['buco@gmail.com'])
            sent = True
    else:
        form = EmailPostForm()

    data = {
            'sections': sections, 
            'sectors': sectors, 
            'stats': stats, 
            'services': services,
            'teams': teams,
            'infos': infos,
            'sent': sent,
            'form': form,
        }
    return render(request, 'landinpage/index.html', data)

def portofolio(request, title):

    service = get_object_or_404(Service, title=title)
    projects = Project.objects.filter(service=service.id)

    print(projects)
    # service = Service.objects.filter(servi)
    # projects = Project.objects.filter(service=id)
    # print(projects)
    data = {
        'projects': projects, 
        'service': service
        }

    return render(request, 'landinpage/portofolio.html', data)

landinpage/templates/landinpage/base.html
{% load static %}
<html>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} Document {% endblock %}</title> 
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="{% static "css/bootstrap/bootstrap.min.css" %}" rel="stylesheet">
    <link href="{% static "css/icofont/icofont.min.css" %}" rel="stylesheet">
    <link href="{% static "css/boxicon/boxicons.min.css" %}" rel="stylesheet">
    <link href="{% static "css/animate/animate.min.css" %}" rel="stylesheet">
    <link href="{% static "css/remixicon/remixicon.css" %}" rel="stylesheet">
    <link href="{% static "css/venobox/venobox.css" %}" rel="stylesheet">    
    <link href="{% static "css/owl/owl.carousel.min.css" %}" rel="stylesheet">
    
    {% comment %} <link href="{% static "css/aos/aos.css" %}" rel="stylesheet">  {% endcomment %}
    

    <!-- Template Main CSS File -->
    <link href="{% static "css/style.css" %}" rel="stylesheet">
    
    {% block link %}  {% endblock %}
</head>

<body>

    <!-- ======= Header ======= -->
    <header id="header" class="fixed-top">
        <div class="container d-flex align-items-center">

        <h1 class="logo mr-auto"><a href="{% url 'landinpage:index' %}" class="ft-sz-05em">BUCO International  </a></h1>
        <!-- Uncomment below if you prefer to use an image logo -->
        <!-- <a href="index.html" class="logo mr-auto"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->

        <nav class="nav-menu d-none d-lg-block">
            <ul>
            <li class="active"><a href="{% url 'landinpage:index' %} ">Accueil</a></li>
            <li><a href="#about">Qui sommes nous ?</a></li>
            <li><a href="#services">Services</a></li>
            <li><a href="#portfolio">Portfolio</a></li>
            <li><a href="#team">Equipe</a></li>
            
            <li><a href="#contact"></a></li>

            </ul>
        </nav><!-- .nav-menu -->

        <a href="#about" class="get-started-btn">Contactez nous</a>

        </div>
    </header><!-- End Header -->

    {% block hero %}  

    {% endblock %}<!-- End hero -->


        
    <main id="main">
        {% block main %}  

        {% endblock %}
    </main><!-- End #main -->


    <!-- ======= Footer ======= -->
    <footer id="footer">
        <div class="footer-top">
        <div class="container">
            <div class="row">

            <div class="col-lg-4 col-md-6">
                <div class="footer-info">
                <h3>Multi</h3>
                <p class="pb-3"><em>Qui repudiandae et eum dolores alias sed ea. Qui suscipit veniam excepturi quod.</em></p>
                <p>
                    A108 Adam Street <br>
                    NY 535022, USA<br><br>
                    <strong>Phone:</strong> +1 5589 55488 55<br>
                    <strong>Email:</strong> info@example.com<br>
                </p>
                <div class="social-links mt-3">
                    <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
                    <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
                    <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
                    <a href="#" class="google-plus"><i class="bx bxl-skype"></i></a>
                    <a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a>
                </div>
                </div>
            </div>

            <div class="col-lg-2 col-md-6 footer-links">
                <h4>Useful Links</h4>
                <ul>
                <li><i class="bx bx-chevron-right"></i> <a href="#">Home</a></li>
                <li><i class="bx bx-chevron-right"></i> <a href="#">About us</a></li>
                <li><i class="bx bx-chevron-right"></i> <a href="#">Services</a></li>
                <li><i class="bx bx-chevron-right"></i> <a href="#">Terms of service</a></li>
                <li><i class="bx bx-chevron-right"></i> <a href="#">Privacy policy</a></li>
                </ul>
            </div>

            <div class="col-lg-2 col-md-6 footer-links">
                <h4>Our Services</h4>
                <ul>
                <li><i class="bx bx-chevron-right"></i> <a href="#">Web Design</a></li>
                <li><i class="bx bx-chevron-right"></i> <a href="#">Web Development</a></li>
                <li><i class="bx bx-chevron-right"></i> <a href="#">Product Management</a></li>
                <li><i class="bx bx-chevron-right"></i> <a href="#">Marketing</a></li>
                <li><i class="bx bx-chevron-right"></i> <a href="#">Graphic Design</a></li>
                </ul>
            </div>

           
            </div>
        </div>
        </div>

        <div class="container">
        <div class="copyright">
            &copy; Copyright <strong><span>BUCO</span></strong>. All Rights Reserved
        </div>
        <div class="credits">
            <!-- All the links in the footer should remain intact. -->
            <!-- You can delete the links only if you purchased the pro version. -->
            <!-- Licensing information: https://bootstrapmade.com/license/ -->
            <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/multi-responsive-bootstrap-template/ -->
            Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
        </div>
        </div>
    </footer><!-- End Footer -->

    <div id="preloader"></div>
    <a href="#" class="back-to-top"><i class="icofont-simple-up"></i></a>

    <!-- Vendor JS Files -->
    <script src="{% static "js/jquery.min.js" %}"></script>
    <script src="{% static "js/bootstrap.bundle.min.js" %}"></script>
    <script src="{% static "js/jquery.easing.min.js" %}"></script>
    <script src="{% static "js/owl.carousel.min.js" %}"></script>
    <script src="{% static "js/aos.js" %}"></script>

    <script src="{% static "js/validate.js" %}"></script>
    <script src="{% static "js/jquery.waypoints.min.js" %}"></script>
    <script src="{% static "js/counterup.min.js" %}"></script>
    <script src="{% static "js/venobox.min.js" %}"></script>
    <script src="{% static "js/isotope.pkgd.min.js" %}"></script>
    
    <!-- Template Main JS File -->
    <script src="{% static "js/main.js" %}"></script>


</body>
</html>

landinpage/templates/landinpage/index.html
{% extends "landinpage/base.html" %}
{% load static %}


{% block hero %}
  <!-- ======= Hero Section ======= -->
  
  <section id="hero">
    <div id="heroCarousel" class="carousel slide carousel-fade" data-ride="carousel">

      <ol class="carousel-indicators" id="hero-carousel-indicators"></ol>

      <div class="carousel-inner" role="listbox">
        {% for section in sections %}
          <!-- Slide 1 -->
          <div class="carousel-item active" style="background-image: url({{section.img.url}})">
            <div class="carousel-container">
              <div class="container">
                <h2 class="animate__animated animate__fadeInDown"> {{section.title}} </h2>
                <p class="animate__animated animate__fadeInUp">{{section.description}}.</p>
                <a href="#about" class="btn-get-started animate__animated animate__fadeInUp scrollto">Qui sommes-nous &#63;</a>
              </div>
            </div>
          </div>
        {% endfor %}
      </div>

      <a class="carousel-control-prev" href="#heroCarousel" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon icofont-simple-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>

      <a class="carousel-control-next" href="#heroCarousel" role="button" data-slide="next">
        <span class="carousel-control-next-icon icofont-simple-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>
  </section><!-- End Hero -->
{% endblock %}

{% block main %}

<!-- ======= About Section ======= -->
    <section id="about" class="about">
      <div class="container" data-aos="fade-up">

        <div class="section-title">
          <h2>A propos</h2>
          <p>Qui sommes-nous &#63;</p>
        </div>

        <div class="row content">
          <div class="col-lg-6">
            <p>
              Business Company International est une entreprise l&eacute;gale cr&eacute;e le <b>28 janvier 2004</b>
              sous le num&eacute;ro IFU <b>28 janvier 2004</b>.

              Nous intervenons dans plusieurs secteurs tels que:
            </p>
           
            <ul>
              {% for sector  in sectors %}
                <li><i class="ri-check-double-line"></i> <b> {{ sector.title }}  </b></li>
              {% endfor %}             
            </ul>
            <p>
              Une entreprise qui vous accompagne au quotidien dans la vie de chaque jour
            </p>

            <a href="#services" class="btn-learn-more">Decouvrez nos services</a>

          </div>
          <div class="col-lg-6 pt-4 pt-lg-0">
            <p>
              <img src=" {% static 'img/logo.png' %}" class="responsive">
            </p>
          </div>
        </div>

      </div>
    </section><!-- End About Section -->




    <!-- ======= Counts Section ======= -->
    <section id="counts" class="counts">
      <div class="container" data-aos="fade-up">

        <div class="row no-gutters">

          <div class="col-lg-3 col-md-6 d-md-flex align-items-md-stretch">
            <div class="count-box">
              <i class="icofont-simple-smile"></i>
              <span data-toggle="counter-up"> {{stats.0.number}} </span>
              <p><strong>{{stats.0.title}}</strong> </p>
              {% comment %} <a href="#">Find out more &raquo;</a> {% endcomment %}
            </div>
          </div>

          <div class="col-lg-3 col-md-6 d-md-flex align-items-md-stretch">
            <div class="count-box">
              <i class="icofont-document-folder"></i>
              <span data-toggle="counter-up">{{stats.1.number}}</span>
              <p><strong>{{stats.1.title}}</strong> </p>
              {% comment %} <a href="#">Find out more &raquo;</a> {% endcomment %}
            </div>
          </div>

          <div class="col-lg-3 col-md-6 d-md-flex align-items-md-stretch">
            <div class="count-box">
              <i class="icofont-live-support"></i>
              <span data-toggle="counter-up">{{stats.2.number}}</span>
              <p><strong>{{stats.2.title}}</strong> </p>
              {% comment %} <a href="#">Find out more &raquo;</a> {% endcomment %}
            </div>
          </div>

          <div class="col-lg-3 col-md-6 d-md-flex align-items-md-stretch">
            <div class="count-box">
              <i class="icofont-users-alt-5"></i>
              <span data-toggle="counter-up">{{stats.3.number}}</span>
              <p><strong>{{stats.3.title}}</strong> </p>
              {% comment %} <a href="#">Find out more &raquo;</a> {% endcomment %}
            </div>
          </div>

        </div>

      </div>
    </section><!-- End Counts Section -->


    <!-- ======= Cta Section ======= -->
    <section id="cta" class="cta">
      <div class="container" data-aos="zoom-in">

        <div class="text-center">
          <h3>Call To Action</h3>
          <p> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
          <a class="cta-btn" href="#">Call To Action</a>
        </div>

      </div>
    </section><!-- End Cta Section -->



    <!-- ======= Services Section ======= -->
    <section id="services" class="services">
      <div class="container" data-aos="fade-up">

        <div class="section-title">
          <h2>Services</h2>
          <p>NOS SERVICES</p>
        </div>


        <div class="row">
         <a href="{{ services.0.get_absolute_url }}">         
            <div class="col-lg-3 col-md-6 d-flex align-items-stretch" data-aos="zoom-in" data-aos-delay="100">            
              <div class="icon-box">
                <div class="icon"><i class="bx bxl-dribbble"></i></div>
                <h4><a href="{{ services.0.get_absolute_url }}">{{services.0.title}}</a></h4>
                <p>{{services.0.description}} </p>
              </div>
            </div>
          </a>

          <a href="{{ services.1.get_absolute_url }}">         
            <div class="col-lg-3 col-md-6 d-flex align-items-stretch" data-aos="zoom-in" data-aos-delay="100">            
              <div class="icon-box">
                <div class="icon"><i class="bx bx-file"></i></div>
                <h4><a href="{{ services.1.get_absolute_url }}">{{services.1.title}}</a></h4>
                <p>{{services.1.description}} </p>
              </div>
            </div>
          </a>

           <a href="{{ services.2.get_absolute_url }}">         
            <div class="col-lg-3 col-md-6 d-flex align-items-stretch" data-aos="zoom-in" data-aos-delay="100">            
              <div class="icon-box">
                <div class="icon"><i class="bx bx-tachometer"></i></div>
                <h4><a href="{{ services.2.get_absolute_url }}">{{services.2.title}}</a></h4>
                <p>{{services.2.description}} </p>
              </div>
            </div>
          </a>

           <a href="{{ services.3.get_absolute_url }}">         
            <div class="col-lg-3 col-md-6 d-flex align-items-stretch" data-aos="zoom-in" data-aos-delay="100">            
              <div class="icon-box">
                <div class="icon"><i class="bx bx-world"></i></div>
                <h4><a href="{{ services.3.get_absolute_url }}">{{services.3.title}}</a></h4>
                <p>{{services.3.description}} </p>
              </div>
            </div>
          </a>

              

        </div>

      </div>
    </section><!-- End Services Section -->


    <!-- ======= Team Section ======= -->
    <section id="team" class="team section-bg">
      <div class="container" data-aos="fade-up">

        <div class="section-title">
          <h2>Equipe</h2>
          <p>NOTRE EQUIPE D'EXPERT</p>
        </div>

        <div class="row">
          {% for member in teams  %}

            <div class="col-xl-3 col-lg-4 col-md-6">
              <div class="member" data-aos="zoom-in" data-aos-delay="100">
                <img src="{{member.team_img.url}} " class="img-fluid" alt="">
                <div class="member-info">
                  <div class="member-info-content">
                    <h4>{{member.name}}</h4>
                    <span>{{member.fonction}} </span>
                    <span>{{member.sector}} </span>
                  </div>
                  {% comment %} <div class="social">
                    <a href=""><i class="icofont-twitter"></i></a>
                    <a href=""><i class="icofont-facebook"></i></a>
                    <a href=""><i class="icofont-instagram"></i></a>
                    <a href=""><i class="icofont-linkedin"></i></a>
                  </div> {% endcomment %}
                </div>
              </div>
            </div>
          {% endfor %}          

        </div><!-- End row -->

      </div><!-- End container -->
    </section><!-- End Team Section -->


    <!-- ======= Contact Section ======= -->
    <section id="contact" class="contact section-bg">
      <div class="container" data-aos="fade-up">

        <div class="section-title">
          <h2>Contact</h2>
          <p>Contact Us</p>
        </div>

        <div class="row">

          <div class="col-lg-6">

            <div class="row">
              <div class="col-md-12">
                <div class="info-box">
                  <i class="bx bx-map"></i>
                  <h3>Ou nous trouver ?</h3>
                  <p>{{infos.adress}} </p>
                </div>
              </div>
              <div class="col-md-6">
                <div class="info-box mt-4">
                  <i class="bx bx-envelope"></i>
                  <h3>Envoyez un eamil </h3>
                  <p>{{infos.mail}} </p>
                </div>
              </div>
              <div class="col-md-6">
                <div class="info-box mt-4">
                  <i class="bx bx-phone-call"></i>
                  <h3>Call Us</h3>
                  <p>+1 5589 55488 55<br>+1 6678 254445 41</p>
                </div>
              </div>
            </div>

          </div>

          <div class="col-lg-6">
          {% if sent %}   
            <div class="email-form center">Votre message a &eacute;t&eacute; bien envoy&eacute; nous vous recontacterons dans les plus bref delai </br>  <b> MERCI  </b> </div>
          {% else %}
            <form  method="post" action=" {% url 'landinpage:index' %} " role="form" class="email-form">
            {% csrf_token %}

              <div class="form-row">
                <div class="col form-group">
                  <input type="text" name="name"  class="form-control"maxlength="50" required="" id="id_name" placeholder="Your Name" data-msg="Please enter at least 4 chars">                 
                    <div class="validate"></div>
                </div>

                <div class="col form-group">
                  <input type="email" class="form-control"  name="email" required="" placeholder="Your Email" id="id_email" data-msg="Please enter a valid email">
                    <div class="validate"></div>
                </div>
              </div>

              <div class="form-group">
                <input type="text" class="form-control" name="subject" data-rule="minlen:4" placeholder="Subject" maxlength="250" required="" id="id_subject " data-msg="Please enter at least 8 chars of subject" >                
                  <div class="validate"></div>
              </div>

              <div class="form-group">
                <textarea name="message" class="form-control" placeholder="Message"  rows="5" cols="40" data-msg="Please write something for us" data-rule="required" required="" id="id_message"></textarea>                
                  <div class="validate"></div>
              </div>

              <div class="mb-3">
                <div class="loading">Loading</div> 
                
                
                  <div class="text-center"><button type="submit">Send Message</button></div>
              
              </div>
            </form>
            {% endif %} 
          </div>

        </div>

      </div>
    </section><!-- End Contact Section -->

{% endblock %}


landinpage/templates/landinpage/portofolio.html
{% extends 'landinpage/base.html' %}
{% load static %}


{% block main %}

<!-- ======= Breadcrumbs ======= -->
    <section id="breadcrumbs" class="breadcrumbs">
      <div class="container">

        <ol>
          <li><a href="{% url 'landinpage:index' %} ">Home</a></li>
          <li> {{service.title}} </li>
        </ol>
        <h2>{{service.title}}</h2>

      </div>
    </section><!-- End Breadcrumbs -->

    <!-- ======= Portfolio Details Section ======= -->
    <section id="portfolio-details" class="portfolio-details">
      <div class="container">

        <div class="portfolio-details-container">

            <div class="owl-carousel portfolio-details-carousel">
              {% for project in projects %}
                <img src="{{ project.project_img.url}} " class="img-fluid" alt="">
              {% endfor %}
            </div>
       
        </div><!-- End portfolio-details-container -->

{% for project in projects  %}
        <div class="row mtop-2">
          
          
              <div class="portfolio-info col-lg-4">
                <h3>Project information</h3>
                  <ul>
                      <li><strong>Category</strong>: {{project.category}} </li>
                      <li><strong>Client</strong>: {{ project.client}}</li>
                      <li><strong>Project date</strong>: {{ project.project_date}}</li>
                      <li><strong>Project URzL</strong>: <a href="{{ project.url}}">{{ project.title}}</a></li>
                  </ul>
              </div>

            <div class="portfolio-description col-lg-8">
                <h2>{{ project.title}}</h2>
                <p>
                    {{ project.description}}
                </p>
            </div><!-- End portfolio-description -->
         
        </div><!-- End row -->

         {% endfor %}
      </div><!-- End container -->

     
    </section><!-- End Portfolio Details Section -->

{% endblock %}